apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlog01-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Marty4FromCPT/mlog01.git
    targetRevision: main
    path: helm-charts/backend
    helm:
      releaseName: backend
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
